### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by franzvezuli** [rob-williams/CityVitalsWatchMod#3]
Hello!

I was a huge fan of your CS1 mod at the Steam workshop here: https://steamcommunity.com/sharedfiles/filedetails/?id=410151616

You inspired me to make my own for City Skylines 2 version, I published it over the weekend here: https://mods.paradoxplaza.com/mods/85643/Windows and I also credited your inspiration at the repo here: https://github.com/franzvezuli/cs2-city-vitals-watch

Wanted to send you a personal email or DM, but I'm not sure how to do it through github, so I hope this reaches you well and that you are doing good!

Thanks,
Franz

**Comment by rob-williams** [comment]
Thanks so much for the kind words!

Your version looks great; congratulations on the release! It's really cool to see this carried forward into CS2.

All the best!
